version: "3.8"

services:
  wg-easy:
    image: weejewel/wg-easy
    container_name: wireguard
    environment:
      - WG_HOST=192.168.127.244
      - PASSWORD=password
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ~/.wg-easy:/etc/wireguard
      - ./html:/usr/share/nginx/html
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped

  web-server:
    image: nginx:latest
    container_name: web-server
    volumes:
      - ./html:/usr/share/nginx/html
    ports:
      - "80:80"
    restart: unless-stopped
